name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Zip Headers
        shell: bash
        working-directory: ${{github.workspace}}
        run: tar -czf sys_string.tar.gz --transform s/lib/sys_string/ lib

      - name: Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: true
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body: ...edit me...
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload headers
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{github.workspace}}/sys_string.tar.gz
          asset_name: sys_string-${{ github.ref_name }}.tar.gz
          asset_content_type: application/gzip
      