name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get release Name
        uses: actions/github-script@v7
        with:
          script: |
            const tagName = context.ref.substring(context.ref.lastIndexOf('/') + 2)
            core.exportVariable('RELEASE_NAME', tagName)

      - name: Zip Headers
        shell: bash
        run: tar -czf sys_string-${{ env.RELEASE_NAME }}.tar.gz --transform s/lib/sys_string/ lib
      
      - name: Make release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          prerelease: false
          name: ${{ env.RELEASE_NAME }}
          body: ...edit me...
          files: |
            sys_string-${{ env.RELEASE_NAME }}.tar.gz

      